configured_endpoints: 5
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/octogen-systems-inc%2Foctogen-api-0594752bffee64c00b8a7d7b31e3633afcfd6e1d244f0cb46c5da3a13f8a5294.yml
openapi_spec_hash: 90b1ba8aaab0dd0fc82ded502b4336b7
config_hash: d3a2b3188c92efb6d37c9e784f6ec9f2
