configured_endpoints: 5
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/octogen-systems-inc%2Foctogen-api-0594752bffee64c00b8a7d7b31e3633afcfd6e1d244f0cb46c5da3a13f8a5294.yml
openapi_spec_hash: 90b1ba8aaab0dd0fc82ded502b4336b7
config_hash: c6b49a982e5ad124150b7e9e1ba07fa5
